# Generated by Django 4.0.5 on 2022-07-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='user',
        ),
    ]
